const Types = {
  LOGIN_BEGIN: 'LOGIN_BEGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SIGNUP_BEGIN: 'SIGNUP_BEGIN',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  FETCH_APPOINTMENTS_BEGIN: 'FETCH_APPOINTMENTS_BEGIN',
  FETCH_APPOINTMENTS_SUCCESS: 'FETCH_APPOINTMENTS_SUCCESS',
  FETCH_APPOINTMENTS_ERROR: 'FETCH_APPOINTMENTS_ERROR',
  FETCH_CARS_BEGIN: 'FETCH_CARS_BEGIN',
  FETCH_CARS_SUCCESS: 'FETCH_CARS_SUCCESS',
  FETCH_CARS_ERROR: 'FETCH_CARS_ERROR',
  FETCH_CAR_BEGIN: 'FETCH_CAR_BEGIN',
  FETCH_CAR_SUCCESS: 'FETCH_CAR_SUCCESS',
  FETCH_CAR_ERROR: 'FETCH_CAR_ERROR',

  //
  SET_CURRENT_USER: 'SET_CURRENT_ USER',
  SET_ERRORS: 'SET_ERRORS',
  SET_LOADING: 'SET_LOADING',
  SET_APPOINTMENTS: 'SET_APPOINTMENTS',
  SET_CARS: 'SET_CARS',
  SET_CAR: 'SET_CAR',
};

export default Types;
