const Types = {
  SET_CURRENT_USER: 'SET_CURRENT_ USER',
  SET_FETCHING: 'SET_FETCHING',
  SET_ERRORS: 'SET_ERRORS',
  SET_LOADING: 'SET_LOADING',
  SET_APPOINTMENTS: 'SET_APPOINTMENTS',
  SET_CARS: 'SET_CARS',
  SET_CAR: 'SET_CAR',
};

export default Types;
