const Types = {
  FETCH_APPOINTMENTS_BEGIN: 'FETCH_APPOINTMENTS_BEGIN',
  FETCH_APPOINTMENTS_SUCCESS: 'FETCH_APPOINTMENTS_SUCCESS',
  FETCH_APPOINTMENTS_ERROR: 'FETCH_APPOINTMENTS_ERROR',
  FETCH_CARS_BEGIN: 'FETCH_CARS_BEGIN',
  FETCH_CARS_SUCCESS: 'FETCH_CARS_SUCCESS',
  FETCH_CARS_ERROR: 'FETCH_CARS_ERROR',
  FETCH_CAR_BEGIN: 'FETCH_CAR_BEGIN',
  FETCH_CAR_SUCCESS: 'FETCH_CAR_SUCCESS',
  FETCH_CAR_ERROR: 'FETCH_CAR_ERROR',

  SET_CURRENT_USER: 'SET_CURRENT_ USER',
  SET_FETCHING: 'SET_FETCHING',
  SET_ERRORS: 'SET_ERRORS',
  SET_LOADING: 'SET_LOADING',
  SET_APPOINTMENTS: 'SET_APPOINTMENTS',
  SET_CARS: 'SET_CARS',
  SET_CAR: 'SET_CAR',
};

export default Types;
